# Based on siplasplas Travis config:
# https://github.com/Manu343726/siplasplas/blob/master/.travis.yml

language: cpp
os: linux
addons:
  apt:
    packages:
      - clang-3.7
      - g++-5 # We need an updated stdlibc++ for clang too
      - gcc-5
      - libboost1.55-all-dev # For Standardese
      - valgrind
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - boost-latest

env:
  global:
    - BUILD_TYPE=Release
    - CLANG_VERSION="3.7"

matrix:
  include:
    # Unit tests:
    - env: PERF_TEST=""                   # unit tests, clang
    - env: PERF_TEST="" GCC_VERSION=5.2.1 # unit tests, gcc
    # Perf tests:
    - env: PERF_TEST="insert_base"                          # insert_base,       clang
    - env: PERF_TEST="insert_base"       GCC_VERSION=5.2.1  # insert_base,       gcc
    - env: PERF_TEST="for_each_base"                        # for_each_base,     clang
    - env: PERF_TEST="for_each_base"     GCC_VERSION=5.2.1  # for_each_base,     gcc
    - env: PERF_TEST="insert_function"                      # insert_function,   clang
    - env: PERF_TEST="insert_function"   GCC_VERSION=5.2.1  # insert_function,   gcc
    - env: PERF_TEST="for_each_function"                    # for_each_function, clang
    - env: PERF_TEST="for_each_function" GCC_VERSION=5.2.1  # for_each_function, gcc
    - env: PERF_TEST="insert_any"                           # insert_any,        clang
    - env: PERF_TEST="insert_any"        GCC_VERSION=5.2.1  # insert_any,        gcc
    - env: PERF_TEST="for_each_any"                         # for_each_any,      clang
    - env: PERF_TEST="for_each_any"      GCC_VERSION=5.2.1  # for_each_any,      gcc

before_install:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ -z "$GCC_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - which $CXX
  - which $CC
  - $CXX --version
  - $CC --version
  - if [ -z "$GCC_VERSION" ]; then which clang++ || true; fi

install:

# From Louis Dionne's Boost.Hana .travis.yml

############################################################################
# All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

############################################################################
# Install a recent CMake
############################################################################
  - CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
  - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}

  - cmake --version

  # Finished building deps
  - cd ${TRAVIS_BUILD_DIR}

  # Configure and build project:
  - if [ ! -d build ]; then mkdir build; fi
  - cd build

  - if [ -n "$PERF_TEST" ]; then export BOOST_POLYCOLLECTION_PERF_ONLY=ON; else export BOOST_POLYCOLLECTION_PERF_ONLY=OFF; fi
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
              -DBOOST_POLYCOLLECTION_PERF_ONLY="$BOOST_POLYCOLLECTION_PERF_ONLY"
              -DBOOST_POLYCOLLECTION_PERF_TESTS="$PERF_TEST"
  - cmake --build .

script:
  - if [ -n "$PERF_TEST" ]; then make run_perf; fi
  - if [ -z "$PERF_TEST" ]; then make run_test_all; fi
